### ISSUE TITLE
Investigate :checkhealth warning

### ISSUE THREAD

**Issue by imbacraft** [simaxme/java.nvim#4]
Hello,

I open this issue to investigate what this warning is when running :checkhealth from inside neovim.

![checkhealth](https://github.com/simaxme/java.nvim/assets/81305364/4bab2d31-bb0f-4125-b961-0f074f0a5fae)

Thank you for your time.

**Comment by simaxme** [comment]
Hello, 
this issue is connected with your configuration file for lazy. You are using an unknown configuration key named "After". 
As I have seen, you have already [fixed this issue](https://github.com/imbacraft/dusk.nvim/commit/71bc0c5cf4faa6d98aaa88b6e4930760116afa73). Therefore, this issue will be closed. 
Have a great time with my plugin 👍

**Comment by imbacraft** [comment]
@simaxme You were correct, the issue was with my lazy.nvim setup. Thanks for investigating.
